Improve tools/bootstrap to be more defensive

diff --git a/tools/bootstrap b/tools/bootstrap
--- a/tools/bootstrap
+++ b/tools/bootstrap
@@ -1,13 +1,19 @@
 #!/bin/sh
 
-
-#this script allows us to make symbolic link of pre-commit file
-#the link of pre-commit file will be inserted in the following dir: .git/hooks
-
-if [ -f "pre-commit" ]; then
-        ln -s -f ../../tools/pre-commit ../.git/hooks/pre-commit
-else
-        echo "Error: file pre-commit doesn't exist in the tools directory!"
-        exit 1
+# Check for existence of git.
+which git >/dev/null
+if [[ $? != 0 ]]; then
+  printf "Failed to find 'git' (please install or update your path)\n"
+  exit 1
 fi
+
+# Get top-level directory so we can look for tools/pre-commit file.
+directory=$(git rev-parse --show-toplevel)
+
+if [[ ! -f "${directory}/tools/pre-commit" ]]; then
+  printf "Failed to find 'tools/pre-commit'"
+  exit 1
+fi
+
+ln -s -f ../../tools/pre-commit "${directory}/.git/hooks/pre-commit"
 
