Improve tools/pre-commit to be more defensive

diff --git a/tools/pre-commit b/tools/pre-commit
--- a/tools/pre-commit
+++ b/tools/pre-commit
@@ -1,77 +1,67 @@
 #!/bin/bash
 
-STYLE=$(git config --get hooks.clangformat.style)
-
-CUR_VERSION_CLANG="$(clang-format --version | head -n1 | cut -d" " -f3)"
-MIN_VERSION_CLANG_REQUIRED="12.0.0"
-
-echo "formatting starts..."
-
-#check if .clang-format file is in the root directory
-if [ -f .clang-format ]; then
-  echo ".clang-format found"
-else
-  echo "Error: .clang-format file is not found!"
+# Check for existence of git.
+which git >/dev/null
+if [[ $? != 0 ]]; then
+  printf "Failed to find 'git' (please install or update your path)\n"
   exit 1
 fi
 
-#check version of clang-format
-if [ "$(printf '%s\n' "$MIN_VERSION_CLANG_REQUIRED" "$CUR_VERSION_CLANG" | sort -V | head -n1)" == "$MIN_VERSION_CLANG_REQUIRED" ]; then
-  echo "clang-format version is correct (${CUR_VERSION_CLANG})"
-  else
-    echo "Error: your version of clang-format is too old! Please, update it!"
-    exit 1
+# Check for existence of clang-format
+which clang-format >/dev/null
+if [[ $? != 0 ]]; then
+  printf "Failed to find 'clang-format' (please install or update your path)\n"
+  exit 1
 fi
 
-#formatting files
-if [ -n "${STYLE}" ] ; then
-  STYLEARG="-style=${STYLE}"
-else
-  STYLEARG=""
-fi
+# Returns 0 if the version in the first argument is greater than or
+# equal to the version in the second argument, otherwise returns 1.
+check_version() {
+  local found="$1"
+  local required="$2"
 
-format_file() {
-  file="${1}"
-  if [ -f $file ]; then
-    clang-format -i ${STYLEARG} ${1}
-    result=$(echo $?)
-    echo "code result from clang-format command = ${result}"
+  # Use 'sort -V' in order to sort the versions and select the "oldest".
+  local oldest="$(printf '%s\n' "${found}" "${required}" | sort -V | head -n1)"
 
-    if [ $result == 0 ]; then
-      echo "clang-format was applied successful."
-    else
-      echo "Error: unsuccessful file formatting."
-      exit 1
-    fi
-
-  fi
+  # Ensure the "oldest" of the two versions is what's required.
+  [[ "${oldest}" == "${required}" ]]
 }
 
-check_format_file() {
-   file="${1}"
-   if [ -f $file ]; then
-     echo "starts checking format of ${file} ..."
-     clang-format --dry-run -Werror --ferror-limit=0  ${1}
-     result=$(echo $?)
+# Check version of clang-format.
+clang_format_version_found="$(clang-format --version | head -n1 | cut -d" " -f3)"
+clang_format_version_required="12.0.0"
 
-     if [ $result == 0 ]; then
-         echo "${file} was formatted correctly."
-     else
-         echo "Error: ${file} wasn't formatted correctly."
-         exit 1
-     fi
-   fi
- }
+check_version ${clang_format_version_found} ${clang_format_version_required}
 
+if [[ $? != 0 ]]; then
+  printf "clang-format version '%s' is required but found '%s'\n" \
+    "${clang_format_version_required}" \
+    "${clang_format_version_found}"
+  exit 1
+fi
 
-case "${1}" in
-  --about )
-    echo "Runs clang-format on source files"
+# Get top-level directory so we can look for .clang-format file.
+directory=$(git rev-parse --show-toplevel)
+
+# Check for .clang-format file.
+if [[ ! -f "${directory}/.clang-format" ]]; then
+  printf "Failed to find '.clang-format' file at '%s'\n" "${directory}"
+  exit 1
+fi
+
+case "$1" in
+  --help )
+    echo "Performs checks on files to be committed"
     ;;
   * )
-    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
-      #format_file "${file}"
-      check_format_file "${file}"
+    files=`git diff-index --cached --name-only HEAD | grep -iE '\.(cc|h)$'`
+    for file in ${files}; do
+      # Check file is formatted correctly.
+      clang-format --dry-run -Werror --ferror-limit=0  ${file}
+      if [ $? != 0 ]; then
+        exit 1
+      fi
+      # TODO: add more pre-commit checks here ...
     done
     ;;
 esac
