just check if specific file was formatted correctly (check_format_file() - function in pre-commit file)

diff --git a/tools/pre-commit b/tools/pre-commit
--- a/tools/pre-commit
+++ b/tools/pre-commit
@@ -48,13 +48,32 @@ format_file() {
 }
 
 
+check_format_file() {
+  file="${1}"
+  if [ -f $file ]; then
+    echo "starts checking format of ${file} ..."
+    clang-format --dry-run -Werror --ferror-limit=0  ${1}
+    result=$(echo $?)
+    
+    if [ $result == 0 ]; then
+        echo "${file} was formatted correctly."
+    else
+        echo "Error: ${file} wasn't formatted correctly."
+        exit 1
+    fi
+  fi
+}
+
+
+
 case "${1}" in
   --about )
     echo "Runs clang-format on source files"
     ;;
   * )
     for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
-      format_file "${file}"
+      #format_file "${file}"
+      check_format_file "${file}"
     done
     ;;
 esac
