updated pre-commit

diff --git a/tools/pre-commit b/tools/pre-commit
--- a/tools/pre-commit
+++ b/tools/pre-commit
@@ -1,11 +1,36 @@
 #!/bin/bash
 
 STYLE=$(git config --get hooks.clangformat.style)
+
+CUR_VERSION_CLANG="$(clang-format --version | head -n1 | cut -d" " -f3)"
+MIN_VERSION_CLANG_REQUIRED="12.0.0"
+
+echo "formatting starts..."
+
+#check if .clang-format file is in the root directory
+if [ -f .clang-format ]; then
+  echo ".clang-format found"
+else
+  echo "Error: .clang-format file is not found!"
+  exit 1
+fi
+
+
+#check version of clang-format
+if [ "$(printf '%s\n' "$MIN_VERSION_CLANG_REQUIRED" "$CUR_VERSION_CLANG" | sort -V | head -n1)" == "$MIN_VERSION_CLANG_REQUIRED" ]; then
+  echo "clang-format version is correct (${CUR_VERSION_CLANG})"
+  else
+    echo "Error: your version of clang-format is too old! Please, update it!"
+    exit 1
+fi
+
+#formatting files
 if [ -n "${STYLE}" ] ; then
   STYLEARG="-style=${STYLE}"
 else
   STYLEARG=""
 fi
+
 
 format_file() {
   file="${1}"
